watchdog:
  check_interval_ms: 1000
  warn_after_missing_signal_for_ms: 2000
  restart_after_missing_signal_for_ms: 5000

source:
  # expected sample-format
  format: S24BE

  # excted sample-rate
  rate: 48000

sources:
# for RAVENNA VS
#- type: rtsp
#  location: rtsp://192.168.178.24:8080/by-id/245599667748866
#  channels: 2

# for Mediornet
#- type: udp
#  channels: 8
#  address: 239.1.42.1
#  iface: enp4s1.3
#  port: 5004

#- type: udp
#  channels: 8
#  address: 239.1.42.2
#  iface: enp4s1.3
#  port: 5004

# for Demo
- type: demo
  channels: 8

- type: demo
  channels: 8

clocking:
  source: system

  #source: ptp
  #ptp_master: 192.168.178.24

  # in Seconds
  #jitterbuffer: 20 # for RAVENNA VS

  # for Mediornet Nexus
  jitterbuffer: false

# name of each channel. unnamed channels will issue a warning and will be named "unnamed/XX"
# channel-names can contains slashes, denoting folders. a wall-clock-timestamp and the filetype suffix will be added to the name
# channel-name "s1/mics/head1" might result in a filename like "s1/mics/head1/2018-01-01_10-00-00.wav
# to *not* record a channel, set its name to the special value "!discard".
channelmap:
  0: "s1/mics/head1"
  1: "s1/mics/head2"

  2: "s1/mics/atmo1"
  3: "s1/mics/atmo2"

  4: "!discard"
  5: "!discard"
  6: "!discard"
  7: "!discard"

  8: "s2/mics/head1"
  9: "s2/mics/head2"

  10: "s2/mics/atmo1"
  11: "s2/mics/atmo2"

  12: "!discard"
  13: "!discard"
  14: "!discard"
  15: "!discard"

capture:
  # can also be specified via command-line arg
  folder: /video/audio-backup/

  # length of a segment in seconds
  segment-length: 5

  # desired capture-format, check supported with `gst-inspect-1.0 wavenc`
  format: S24LE

status_server:
  port: 9999
  bind: '::'
  level_interval_ms: 250
  system_health_report_interval_ms: 1000
